<header>
        <div class="header-content">
            <div class="header-content-inner">
                <img src="<?=$theme_url;?>/images/logos/tyn-media-header.png"/>
                <hr>
                <p itemprop="description"><a itemprop="url" href="http://www.tynmediagroup.com"><span itemprop="name"><strong>TyN Media Group</strong></span></a> leading technology news website network in Latin America, with more than 20 websites focused on the latest tech&biz's news.</p>
                <?php //<a href="#about" class="btn btn-primary btn-xl page-scroll">¡Conozca más sobre nosotros!</a>;?>
            </div>
        </div>
    </header>
 <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">About</h2>
                    <hr class="light">
                    <p class="text-faded">TyN Media Group is a media platform that includes 24 Technology and Business specialised sites focused on LATAM, US Hispanic and Spain. After 10 years on the market, we are proud to say that there is no other media company in the industry that gets more traffic than us.
					<p class="text-faded">Our publications are based on verticals (themes) and countries. We recognise the importance that technology has in our daily lives so, TyN Media Group focuses on specialised topics: most important news on governments, innovation and developments which influence the economy, enterprises, small companies, students and executives. All of them with a huge desire to learn and follow where the human ingenuity will lead us.</p>
					<p class="text-faded">Thanks to the influence generated by the technology on our daily life, TyN Media Group interviews the best executives in the industry. Experts to show us their greatest work which is published all over our 24 sites.</p>
					<p class="text-faded">We are glad to generate ideas, publications and open spaces such as conferences and shows to promote education on technology and business.</p>
                    <?php //<a href="#" class="btn btn-default btn-xl">Get Started!</a>;?>
                </div>
            </div>
        </div>
    </section>

    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Metrics</h2>
                    <hr class="primary">
					<p>Transnational corporations, small businesses, students and executives. All of them with a huge desire to learn and follow where the human ingenuity will lead us.</p>
                </div>
            </div>
        </div>
        <div class="container">
			<div class="row">
					<div class="col-lg-3 col-md-6 text-center">
						<div class="service-box">
							<i class="fa fa-4x fa-arrow-circle-up wow bounceIn text-primary"></i>
							<h3>500.000 monthly visitors</h3>
						</div>
					</div>
					<div class="col-lg-3 col-md-6 text-center">
						<div class="service-box">
							<i class="fa fa-4x fa-eye wow bounceIn text-primary" data-wow-delay=".1s"></i>
							<h3>625.000 monthly page views</h3>                       
						</div>
					</div>
					<div class="col-lg-3 col-md-6 text-center">
						<div class="service-box">
							<i class="fa fa-4x fa-clock-o wow bounceIn text-primary" data-wow-delay=".1s"></i>
							<h3>5,5' time/page</h3>
						</div>
					</div>
					<div class="col-lg-3 col-md-6 text-center">
						<div class="service-box">
							<i class="fa fa-4x fa-desktop wow bounceIn text-primary" data-wow-delay=".1s"></i>
							<h3>2.165.000 monthly sessions</h3>                        
						</div>
					</div>
			</div>
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-hand-o-up wow bounceIn text-primary"></i>
                        <h3>2,33 page/session</h3>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-globe wow bounceIn text-primary" data-wow-delay=".1s"></i>
                        <h3>18 countries: regional pressence</h3>                       
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-bullseye wow bounceIn text-primary" data-wow-delay=".1s"></i>
                        <h3>680.000 banner impressions</h3>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-line-chart wow bounceIn text-primary" data-wow-delay=".1s"></i>
                        <h3>CRT: 0,33%</h3>                        
                    </div>
                </div>
            </div>
        </div>
    </section>

   <section id="staff" class="bg-dark">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Who Are We</h2>
                    <hr class="primary">
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4 col-sm-6 text-center">
                    <div class="service-box" itemscope itemtype="http://schema.org/Person">
                        <h3 itemprop="name">GUSTAVO MARTINEZ</h3>
                        <p class="text-muted" itemprop="jobtitle">Editorial director</p>
                        <p class="text-muted"><a href="mailto:gustavom@tynmagazine.com" target="_blank"><span itemprop="email">gustavom@tynmagazine.com</spam></a></p>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 text-center">
                    <div class="service-box" itemscope itemtype="http://schema.org/Person">
                        <h3 itemprop="name">JUAN GNIUS</h3>
                        <p class="text-muted" itemprop="jobtitle">Editor in Chief</p>
                        <p class="text-muted"><a href="mailto:juang@tynmagazine.com" target="_blank"><span itemprop="email">juang@tynmagazine.com</span></a></p>
                    </div>
                </div>
				<div class="col-lg-4 col-sm-6 text-center">
                    <div class="service-box" itemscope itemtype="http://schema.org/Person">
                        <h3 itemprop="name">FELIPE LAMUS</h3>
                        <p class="text-muted" itemprop="jobtitle">Editor</p>
                        <p class="text-muted"><a href="mailto:felipep@tynmagazine.com" target="_blank"><span itemprop="email">felipep@tynmagazine.com</span></a></p>
                    </div>
                </div>
				<div class="col-lg-4 col-sm-6 text-center">
                    <div class="service-box" itemscope itemtype="http://schema.org/Person">
                        <h3 itemprop="name">RAFAEL PRIETO</h3>
                        <p class="text-muted" itemprop="jobtitle">Editor</p>
                        <p class="text-muted"><a href="mailto:rafaelp@tynmagazine.com" target="_blank"><span itemprop="email">rafaelp@tynmagazine.com</span></a></p>
                    </div>
                </div>
            </div>
        </div>
    </section>
	
	<section id="ads">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Native advertising</h2>
                    <hr class="primary">
					<p>TyN Media Group offers brands a great possibility on native advertising. A great way to promote your product or service and at the same time engage the right audience, make them participate, share and even create more content from it.
					<p>We can create a big variety of content to match your marketing plans and reach the sales you are looking for. Video. Text. Infographics. Photos. All the formats you need for your 4Cs.</p>
                </div>
            </div>
            <div class="row" style="margin-top: 5%;">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Display advertising</h2>
                    <hr class="primary">
					<p>TyN Media Group offers brands a great possibility on display advertising. Classic, for some the best way to promote a product on a website. You are in charge of whatever you want to advertise. Do you want to increase traffic to your site or to sell more? both are great reasons to set a banner with in any of our 24 sites.</p>
					<p>By using different messages on your banner you can provoque curiosity and make our audience clic on your ad. The regular size 250px x 300px is what our clients use the most, however if you have other ad size, just let us know.</p>
                </div>
            </div>
        </div>
    </section>
	 <section class="no-padding" id="portfoliov">
		<div class="col-lg-12 text-center">
			<h2 class="section-heading">Verticals: Sites by themes</h2>
				<hr class="primary">
        </div>
        <div class="container-fluid">
            <div class="row no-gutter">
                <div class="col-lg-4 col-sm-6">
                    <a href="http://www.tynmagazine.com" class="portfolio-box">
                        <img src="<?=$theme_url;?>/images/shots/tynmag-screenshoot.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    TyN Magazine
                                </div>
                                <div class="project-name">
                                    The most important global tech trends and their influences in our daily life. Analysis. Opinion. News.
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
				<div class="col-lg-4 col-sm-6">
                    <a href="http://www.tyniot.com" class="portfolio-box">
                        <img src="<?=$theme_url;?>/images/shots/tyniot-screenshoot.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    TyN IoT
                                </div>
                                <div class="project-name">
                                    The first spanish site dedicated to the Internet of Things: Where the future is now.
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="http://www.tynmobile.com" class="portfolio-box">
                        <img src="<?=$theme_url;?>/images/shots/tynmob-screenshoot.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    TyN Mobile
                                </div>
                                <div class="project-name">
                                    A window to the latest news on mobile & wireless technology. The “mobile” is where we are, everything the consumers know as mobile.
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="http://www.tyntelcos.com" class="portfolio-box">
                        <img src="<?=$theme_url;?>/images/shots/tyntel-screenshoot.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    TyN Telcos
                                </div>
                                <div class="project-name">
                                    Focus on regulations within different countries and world wide. All about telecommunications and its challenges.
								</div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="http://www.tynchannel.com" class="portfolio-box">
                        <img src="<?=$theme_url;?>/images/shots/tyncha-screenshoot.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    TyN Channel
                                </div>
                                <div class="project-name">
								Value information to the channel. Always specific and technical aspects that matters. Analysis. Opinion. News. Business that influence..
								</div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="http://www.tyncloud.com" class="portfolio-box">
                        <img src="<?=$theme_url;?>/images/shots/tynclo-screenshoot.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    TyN Cloud
                                </div>
                                <div class="project-name">
								The latest information about cloud computing and related services. Everything to understand it and where it is taking us.
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
				 <div class="col-lg-4 col-sm-6">
                    <a href="http://www.tyngovernments.com" class="portfolio-box">
                        <img src="<?=$theme_url;?>/images/shots/tyngov-screenshoot.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    TyN Governments
                                </div>
                                <div class="project-name">
									Technology for governments and public administrations. Law and politics, and their impact in the people.
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
				 <div class="col-lg-4 col-sm-6">
                    <a href="http://www.tyninvestment.com" class="portfolio-box">
                        <img src="<?=$theme_url;?>/images/shots/tyninv-screenshoot.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    TyN Investment
                                </div>
                                <div class="project-name">
								All the investments and its variables in technology. Who buys, what, when and where.
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
				 <div class="col-lg-4 col-sm-6">
                    <a href="http://www.tynentrepreneurs.com" class="portfolio-box">
                        <img src="<?=$theme_url;?>/images/shots/tynent-screenshoot.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    TyN Entrepreneurs
                                </div>
                                <div class="project-name">
								The place created for the Entrepreneurs on tech business: news to help on developments and productivity.
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
				<div class="col-lg-4 col-sm-6">
                    <a href="http://www.tynsecurity.com" class="portfolio-box">
                        <img src="<?=$theme_url;?>/images/shots/tynsec-screenshoot.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    TyN Security
                                </div>
                                <div class="project-name">
									One of the most important issues in technology has its own site in TyN Media Group: Security. News, challenges, advances, prices and more.
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>
	<section class="no-padding" id="portfolioc"  style="margin-top: 5%">
		<div class="col-lg-12 text-center">
			<h2 class="section-heading">Sites by countries</h2>
			<hr class="primary">
		</div>
        <div class="container-fluid">
            <div class="row no-gutter">
                <div class="col-lg-4 col-sm-6">
                    <a href="http://www.tynargentina.com" class="portfolio-box">
                        <img src="<?=$theme_url;?>/images/shots/tyn-arg-screenshot.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    TyN Argentina
                                </div>
                                <div class="project-name">
                                    Latest news about tech&biz in Argentina.
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                 <div class="col-lg-4 col-sm-6">
                    <a href="http://www.tynbrasil.com" class="portfolio-box">
                        <img src="<?=$theme_url;?>/images/shots/tyn-bra-screenshot.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    TyN Brasil
                                </div>
                                <div class="project-name">
                                    Latest news about tech&biz in Brazil.
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
				 <div class="col-lg-4 col-sm-6">
                    <a href="http://www.tynecuador.com" class="portfolio-box">
                        <img src="<?=$theme_url;?>/images/shots/tyn-ecu-screenshot.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    TyN Ecuador
                                </div>
                                <div class="project-name">
                                    Latest news about tech&biz in Ecuador.
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
				 <div class="col-lg-4 col-sm-6">
                    <a href="http://www.tynparaguay.com" class="portfolio-box">
                        <img src="<?=$theme_url;?>/images/shots/tyn-par-screenshot.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    TyN Paraguay
                                </div>
                                <div class="project-name">
                                    Latest news about tech&biz in Paraguay.
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
				 <div class="col-lg-4 col-sm-6">
                    <a href="http://www.tynmexico.com" class="portfolio-box">
                        <img src="<?=$theme_url;?>/images/shots/tyn-mex-screenshot.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    TyN México
                                </div>
                                <div class="project-name">
                                    Latest news about tech&biz in Mexico.
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
				 <div class="col-lg-4 col-sm-6">
                    <a href="http://www.tynpanama.com" class="portfolio-box">
                        <img src="<?=$theme_url;?>/images/shots/tyn-pan-screenshot.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    TyN Panamá
                                </div>
                                <div class="project-name">
                                    Latest news about tech&biz in Panama.
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Contact</h2>
                    <hr class="primary">
                    <p>You can contact us to gain pressence in the leading tecnology news network of Latin America.</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center" itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
					<i class="fa fa-map-marker fa-3x wow bounceIn" data-wow-delay=".1s"></i>
					<p><span itemprop="streetAddress">Estados Unidos 3765 - PB 3</span><br>
					<span itemprop="addressLocality">Ciudad de Buenos Aires</span> - (<span itemprop="postalCode">C1228ABO</span>)<br>
					<span itemprop="addressCountry">Argentina</p>
				</div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                    <p><a href="mailto:comercial@tynmagazine.com"><span itemprop="email">comercial@tynmagazine.com</span></a></p>
					<i class="fa fa-phone fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                    <p><span itemprop="telephone">+54 (11) 4956-0948</span></p>
                </div>
            </div>
        </div>
    </section>